version: '3.8'
services:
  web:
    image: node:20
    container_name: tp3_solution_iot
    working_dir: /app
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8083:8083"
    command: bash -c "npm install && npm start"
  
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://root:example@mongo:4500/"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "4500:4500"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
